update readme & ignore

diff --git a/git-release-automator b/git-release-automator
--- a/git-release-automator
+++ b/git-release-automator
@@ -19,11 +19,7 @@ function create_and_push_git_tag()
 {
     new_tag=$1
 
-    # Create git tag
-    echo "git tag $new_tag"
     git tag $new_tag
-
-    # Push tag to remote repository
     git push origin $new_tag
 
     # Display success message
@@ -41,6 +37,7 @@ function get_current_release_branch()
 # Check if the current branch is a release branch
 function create_release_branch()
 {
+  current_branch=$(git branch --show-current)
   local release_branch_name="release/$1"
 
   # Try to switch to an existing release branch
@@ -48,20 +45,19 @@ function create_release_branch()
 
   if [ -z "$release_branch" ]; then
       # Create a new release branch
-      git checkout -b $release_branch_name > /dev/null
+      git checkout -b $release_branch_name 2>/dev/null
       git push origin $release_branch_name > /dev/null
       echo "Created release branch $release_branch_name"
-  else
-      git checkout $release_branch > /dev/null
-      echo "Switched to existing release branch $release_branch_name"
   fi
+
+  git checkout $current_branch 2>/dev/null
 }
 
 if [ -d ".git" ]; then
 	# Get the latest git tag
-	git fetch --all --tags --prune > /dev/null
+	git fetch --all --tags --prune 2>/dev/null
 
-	latest_origin_tag=$(git ls-remote --tags origin | awk '{print $2}' | grep -v '{}' | awk -F"/" '{print $3}' | grep -v '@' | sort -V | tail -1)
+  latest_origin_tag=$(git ls-remote --tags origin | awk '{print $2}' | grep -v '{}' | awk -F"/" '{print $3}' | grep -v '@' | sort -V | tail -1)
   tag_prefix=$(echo $latest_origin_tag | grep -E '^v')
   latest_tag=$(echo $latest_origin_tag | sed 's/^v//')
 
@@ -110,18 +106,19 @@ if [ -d ".git" ]; then
     read -n 1 -r -p "Your choice: " choice
     echo
 
-    if [ "$choice" == "y" ]; then
-        # Create and push the new git tag with "v"
-        new_tag="v1.0.0"
-        create_and_push_git_tag $new_tag
-    elif [ "$choice" == "n" ]; then
-        # Create and push the new git tag without "v"
-        new_tag="1.0.0"
-        create_and_push_git_tag $new_tag
-    else
-        echo "Invalid input."
-        exit 1
-    fi
+    case $choice in
+        y|n)
+            # Create and push the new git tag without "v"
+            new_tag=$(if [[ "$choice" == "y" ]]; then echo "v"; fi)1.0.0
+                create_release_branch $new_tag
+                create_and_push_git_tag $new_tag
+            ;;
+        *)
+            echo "Invalid input."
+            exit 1
+            ;;
+    esac
+
   fi
 else
   echo "This directory does not contain a Git repository."
